SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `neptune_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` mediumtext COLLATE utf8_bin NOT NULL,
  `displayname` mediumtext COLLATE utf8_bin NOT NULL,
  `password` mediumtext COLLATE utf8_bin NOT NULL,
  `email` mediumtext COLLATE utf8_bin,
  `email_public` tinyint(1) NOT NULL DEFAULT '0',
  `permissions` int(11) NOT NULL DEFAULT '1',
  `joined` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `postcount` int(11) NOT NULL DEFAULT '0',
  `avatar_type` int(11) NOT NULL DEFAULT '0',
  `avatar` longtext COLLATE utf8_bin,
  `signature` longtext COLLATE utf8_bin,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=12 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
